// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from fibonacci.djinni

#pragma once

#include <cstdint>
#include <memory>

namespace Fibonacci {

class FibonacciCallbackDjinni;

class FibonacciEngineDjinni {
public:
    virtual ~FibonacciEngineDjinni() {}

    virtual int64_t computeFibonacci(int64_t amount) = 0;

    static std::shared_ptr<FibonacciEngineDjinni> create_with_callback(const std::shared_ptr<FibonacciCallbackDjinni> & callback);
};

}  // namespace Fibonacci
