// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from fibonacci.djinni

#pragma once

#include <cstdint>
#include <vector>

namespace Fibonacci {

class FibonacciCallbackDjinni {
public:
    virtual ~FibonacciCallbackDjinni() {}

    virtual void reportProgress(const std::vector<int64_t> & fibonacciSequenceChunk) = 0;
};

}  // namespace Fibonacci
