// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from fibonacci.djinni

#pragma once

#include "djinni_support.hpp"
#include "fibonacci_engine_djinni.hpp"

namespace Fibonacci {

class NativeFibonacciEngineDjinni final : ::djinni::JniInterface<::Fibonacci::FibonacciEngineDjinni, NativeFibonacciEngineDjinni> {
public:
    using CppType = std::shared_ptr<::Fibonacci::FibonacciEngineDjinni>;
    using JniType = jobject;

    using Boxed = NativeFibonacciEngineDjinni;

    ~NativeFibonacciEngineDjinni();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeFibonacciEngineDjinni>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<NativeFibonacciEngineDjinni>::get()._toJava(jniEnv, c)}; }

private:
    NativeFibonacciEngineDjinni();
    friend ::djinni::JniClass<NativeFibonacciEngineDjinni>;
    friend ::djinni::JniInterface<::Fibonacci::FibonacciEngineDjinni, NativeFibonacciEngineDjinni>;

};

}  // namespace Fibonacci
