// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from fibonacci.djinni

package ch.fork.djinnisample.djinni_generated;

import java.util.concurrent.atomic.AtomicBoolean;

/** definitition of the C++ interface to be called from Java */
public abstract class FibonacciEngineDjinni {
    public abstract long computeFibonacci(long amount);

    /** factory method to create a fibonacci engine with a callback to Java */
    public static native FibonacciEngineDjinni createWithCallback(FibonacciCallbackDjinni callback);

    private static final class CppProxy extends FibonacciEngineDjinni
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public long computeFibonacci(long amount)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_computeFibonacci(this.nativeRef, amount);
        }
        private native long native_computeFibonacci(long _nativeRef, long amount);
    }
}
