// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from fibonacci.djinni

package ch.fork.djinnisample.djinni_generated;

public abstract class FibonacciCallbackDjinni {
    public abstract void reportProgress(String progress);
}
