// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from fibonacci.djinni

package ch.fork.djinnisample.djinni_generated;

import java.util.ArrayList;

/** definitition of the Java callback interface */
public abstract class FibonacciCallbackDjinni {
    public abstract void reportProgress(ArrayList<Long> fibonacciSequenceChunk);
}
